version: "3.9"

services:
  backend:
    build: .
    container_name: suplify-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - kafka
    volumes:
      - .:/usr/src/app
      - /usr/src/app
    command: pnpm run dev
#  🔁 Why remove - /usr/src/app/node_modules?
#If you mount an empty named volume (/usr/src/app/node_modules), it overrides the real node_modules from the image → your app breaks because modules are missing inside container.
# For development, just mount your code and let the image keep its node_modules.
  redis:
    image: redis:7-alpine
    container_name: suplify-redis
    restart: always
    ports:
      - "6380:6379"

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: suplify-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
